---
    - name: Install Required Libraries and Dependencies
      apt:
        name: "{{ item }}"
        state: latest
      loop:
        - autoconf
        - libc6
        - gcc
        - make
        - wget
        - unzip
        - apache2
        - php
        - libapache2-mod-php
        - libgd-dev
        - openssl
        - libssl-dev
        - bc
        - gawk
        - dc
        - build-essential
        - snmp
        - libnet-snmp-perl
        - gettext
        - python3
        - python3-pip

    - name: Install Passlib Python Package
      pip:
        name: passlib

    - name: Create Nagios Directory
      file:
        path: ~/nagios
        state: directory

    - name: Download Nagios Core
      get_url:
        url: https://github.com/NagiosEnterprises/nagioscore/archive/nagios-4.4.6.tar.gz
        dest: ~/nagios/nagioscore.tar.gz
      register: nagios_download

    - name: Extract Nagios Core Archive
      unarchive:
        src: "{{ nagios_download.dest }}"
        dest: ~/nagios
        remote_src: yes
        mode: 0777
        owner: root
        group: root
      when: nagios_download.failed == False

    - name: Download Nagios Plugins
      get_url:
        url: https://github.com/nagios-plugins/nagios-plugins/archive/release-2.3.3.tar.gz
        dest: ~/nagios/nagios-plugins.tar.gz
      register: plugins_download

    - name: Extract Nagios Plugins Archive
      unarchive:
        src: "{{ plugins_download.dest }}"
        dest: ~/nagios
        remote_src: yes
        mode: 0777
        owner: root
        group: root
      when: plugins_download.failed == False

    - name: Compile and Install Nagios Core
      shell: |
        cd ~/nagios/nagioscore-*
        sudo ./configure --with-httpd-conf=/etc/apache2/sites-enabled
        sudo make all
        sudo make install-groups-users
        sudo usermod -a -G nagios www-data
        sudo make install
        sudo make install-daemoninit
        sudo make install-commandmode
        sudo make install-config
        sudo make install-webconf
        sudo a2enmod rewrite
        sudo a2enmod cgi
      register: nagios_core_install

    - name: Compile and Install Nagios Plugins
      shell: |
        cd ~/nagios/nagios-plugins*
        ./tools/setup
        ./configure
        make
        make install
      register: plugins_install

    - name: Add Users to Nagios
      community.general.htpasswd:
        path: /usr/local/nagios/etc/htpasswd.users
        name: admin
        password: admin

    - name: Start and Enable Nagios Service
      service:
        name: nagios
        state: started
        enabled: true

    - name: Restart and Enable Apache/HTTPD Service
      service:
        name: apache2
        state: restarted
        enabled: true
